version: "3.8"

volumes:
    pgdata:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_drweb
    network_mode: bridge
    hostname: postgres_drweb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    env_file: ./postgres.env

  core:
    build: .
    container_name: core_drweb
    hostname: core_drweb
    command: uvicorn application:app --host 0.0.0.0 --port 8000
    network_mode: bridge
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
    links:
      - postgres
    env_file:
      - ./postgres.env
      - ./global.env


